export const GOT_ALL_STUDENTS = "GOT_ALL_STUDENTS"
export const GOT_STUDENT_BY_ID = "GOT_STUDENT_BY_ID"
export const DELETED_STUDENT = "DELETED_STUDENT"
export const CREATED_STUDENT = "CREATED_STUDENT"
export const UPDATED_STUDENT = "UPDATED_STUDENT"

export const GOT_ALL_CAMPUSES = "GOT_ALL_CAMPUSES"
export const GOT_CAMPUS_BY_ID = "GOT_CAMPUS_BY_ID"
export const DELETED_CAMPUS = "DELETED_CAMPUS"
