export const GOT_ALL_STUDENTS = "GOT_ALL_STUDENTS";
export const GOT_STUDENT_BY_ID = "GOT_STUDENT_BY_ID";
export const CREATED_STUDENT = "CREATED_STUDENT";

export const GOT_ALL_CAMPUSES = "GOT_ALL_CAMPUSES";
export const GOT_CAMPUS_BY_ID = "GOT_CAMPUS_BY_ID";
export const CREATED_CAMPUS = "CREATES_CAMPUS";
